setwd("Documents/Github/Ecological-Genomics-2020")
setwd (Ecological-Genomics-2020)
library(DESeq2)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(ggpubr)
library(wesanderson)
library(vsn)
BiocManager::install("vsn")
BiocManager::install("hexbin")
countsTable <- read.table("RS_cds2kb_countsMatrix.txt", header=TRUE, row.names=1)
head(countsTable)
dim(countsTable)
countsTableRound <- round(countsTable) # Need to round because DESeq wants only integers
head(countsTableRound)
conds <- read.delim("RS_samples.txt", header=TRUE, stringsAsFactors = TRUE, row.names=1, colClasses=c('factor', 'factor', 'factor', 'factor'))
head(conds)
dim(conds)
colSums(countsTableRound)
mean(colSums(countsTableRound))
barplot(colSums(countsTableRound), las=3, cex.names=0.5,names.arg = substring(colnames(countsTableRound),1,13))
abline(h=mean(colSums(countsTableRound)), col="blue", lwd =2)
dds <- DESeqDataSetFromMatrix(countData = countsTableRound, colData = conds, design = ~ pop + day + treatment)
summary(dds)
dds <- dds[rowSums(counts(dds))>76]
dds <- DESeqDataSetFromMatrix(countData = countsTableRound, colData = conds, design = ~ climate + day + treatment)
summary(dds)
dds < - DESeq(dds)
str(countsTableRound)
str(conds)
dim(dds)
dds <- dds[rowSums(counts(dds))>76]
dds <- DESeqDataSetFromMatrix(countData = countsTableRound, colData = conds, design = ~ day + climate + treatment)
summary(dds)
dds <- DESeq(dds)
install.packages("pheatmap")
resultsNames(dds)
res <-results(dds, alpha =0.05)

